/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.buildamelody;

public class Main {


    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());
    }
}
